### ISSUE TITLE
最近在做vue3.x的版本，有用到的兄弟可以讲一下需求

### ISSUE THREAD

**Issue by Alfred-Skyblue** [Alfred-Skyblue/v-form-antd#2]

**Comment by ziyingjie** [comment]
最近有在研究 需求其实和v2版本一样 大同小异，v3现在势头正足，期待大佬早日重构成功

**Comment by M4yi** [comment]
能不能考虑添加表单字段间的联动

**Comment by Alfred-Skyblue** [comment]
> 不能考虑添加形式的字段间联

这个功能在vue2里面是有的，vue3里面看情况，表单联动对vue3来说是比较简单的，监听一下属性变化就可以了，如果在设计器里面做的话，需要初始化的时候去遍历所有的，也是会通过watch去监听，不过会比较耗费性能

**Comment by colinin** [comment]
最近做低代码设计找到了这个项目，@Alfred-Skyblue 你介意我用vue3与antdv3版本迁移到我的存储库中吗，我会在README中注明来源，
